name: Manual Test Suite Run

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select the test to run'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - compare_only

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test_type: [full, compare_only]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        if [ "${{ github.event.inputs.test_type }}" == "full" ]; then
          pytest -v -s
        elif [ "${{ github.event.inputs.test_type }}" == "compare_only" ]; then
          pytest -v -k "test_symbols_missing_in_ui or test_extra_symbols_in_ui"
        fi
